# Generated by Django 3.0.4 on 2020-03-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.ForeignKey(help_text='Select a title for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Title'),
        ),
    ]
