# Generated by Django 3.0.4 on 2020-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='book.Genre'),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
