# Generated by Django 3.0.4 on 2020-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200310_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='journal',
        ),
        migrations.AddField(
            model_name='book',
            name='journal',
            field=models.ManyToManyField(to='book.Journal'),
        ),
    ]
